### Get all persons
GET https://fullstackopensubmissions.onrender.com/api/persons

### Get specific person
GET https://fullstackopensubmissions.onrender.com/api/persons/1

### Create new person
POST https://fullstackopensubmissions.onrender.com/api/persons
Content-Type: application/json

{
    "name": "Mateo Duque",
    "number": "8888-0000-8080"
}

### Delete person
DELETE https://fullstackopensubmissions.onrender.com/api/persons/1

### Test home route
GET https://fullstackopensubmissions.onrender.com/

### Test info route
GET https://fullstackopensubmissions.onrender.com/info